-- Create custom_activities table for dynamic activities
CREATE TABLE IF NOT EXISTS public.custom_activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.custom_activities ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (or change according to your role preferences)
CREATE POLICY "Allow public read access to custom_activities" ON public.custom_activities
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert access to custom_activities" ON public.custom_activities
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow public update access to custom_activities" ON public.custom_activities
    FOR UPDATE TO public USING (true) WITH CHECK (true);

CREATE POLICY "Allow public delete access to custom_activities" ON public.custom_activities
    FOR DELETE TO public USING (true);
